spring:
 mvc:
  view.prefix: /WEB-INF/jsp/
  view.suffix: .jsp
 aop:
   auto: true
   
---

server:
 port: 9440
 ssl:
  enabled: true
  key-store: C:\Users\jnatanas\keystore.jks
  key-store-password: password